spring:
  application:
    name: users-ws

  rabbitmq:
    username: user
    password: password

  devtools:
    restart:
      enabled: true

    bus:
      enabled: true
      refresh:
        enabled: true

  h2:
    console:
      path: /h2-console
      enabled: true
      settings.web-allow-others: true

#  datasource:
#    url: jdbc:mysql://localhost:3306/photo_app_users?createDatabaseIfNotExist=true
#    username: root
#    password: peanutbutter

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      enabled: true
      show-details: always
      circuitbreakers:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.dimitarrradev.photoapp.api.users.config.AlbumsServiceClient: "debug"
    com.dimitarrradev.photoapp.api.users.service.UsersService: "debug"
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

resilence4j.circuitbreaker:
  instances:
    albums-ws:
      failureRateThreshold: 50
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 2
      minimumNumberOfCalls: 1
      eventConsumerBufferSize: 10

resilience4j.retry:
  instances:
    albums-ws:
      maxAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 5

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
  retry:
    retryAspectOrder: 2
