spring:
  application:
    name: users-ws

  config:
    import: optional:configserver:http://localhost:8088

  rabbitmq:
    username: user
    password: password

  devtools:
    restart:
      enabled: true

  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

  h2:
    console:
      path: /h2-console
      enabled: true
      settings.web-allow-others: true

  datasource:
    urL: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${PORT:0}

gateway:
  ip: ${GATEWAY_IP}

login:
  url:
    path: "/users/login"
